test_env = Environment(CPPPATH= ['/opt/intel/vcl/include/',
                                 '/opt/intel/vcl/src/',
                                 '/opt/intel/vdms/include/',
                                ],
                      CXXFLAGS= "-std=c++11 -O3")

test_env.Program('main',
        [
        'unit_tests/main.cc',
        'unit_tests/helpers.cc',
        'unit_tests/TDBImage_test.cc',
        'unit_tests/ImageData_test.cc',
        'unit_tests/Image_test.cc',
        'unit_tests/DescriptorSetAdd_test.cc',
        'unit_tests/DescriptorSetClassify_test.cc',
        'unit_tests/DescriptorSetTrain_test.cc',
        'unit_tests/DescriptorSetReadFS_test.cc',
        'unit_tests/DescriptorSetStore_test.cc',
         ],

        LIBS = ['tiledb',
                'opencv_core',
                'opencv_imgproc',
                'opencv_imgcodecs',
                'gomp',
                'faiss',
                'vcl', 'gtest', 'pthread',
                 ],

        LIBPATH = ['/usr/local/lib/', '../',
                   '/opt/facebook/faiss',
                   '/opt/intel/mkl/lib/intel64/'
                   ],

        LINKFLAGS="-Wl,--no-as-needed",
    )
